carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add')
]

tienda/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import ProductListView
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls'))
]

#Permitira usar/mostrar las imagenes
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  {% include 'navbar.html' %}
  <div class="container">
    {% include 'messages.html' %}
    <div class="row mt-5">
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>
<script src="https://kit.fontawesome.com/9603edc1c0.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
</script>

</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
Index
{% endblock %}
{% block content %}
<div class="col">
	<h4 class="text-center">{{message}}</h4>
	{% include 'products/snippets/search.html' %}
	{% include 'products/snippets/list.html' %}
</div>
{% endblock %}

templates/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success' %}
<div class="alert alert-success">
  <button class="close" type="button" data-dismiss="alert">X</button>
  {{message}}
</div>
{% else %}
<div class="alert alert-danger">
  {{message}}
</div>
{%endif%} {% endfor %} {% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a href="{% url 'index' %}" class="navbar-brand">Tienda</a>
  <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse"
    data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse hide" id="navb">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link {% if request.path == cart %}active{% endif %} " href="{{ cart }}">
          Mi carrito<span class="fas fa-shopping-cart"></span>
        </a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="navbar-item">
        <a href="{% url 'logout' %}" class="nav-link">
          <span class="fas fa-sign-in-alt"></span>
          Logout
        </a>
      </li>
      {% else %}
      <li class="navbar-item {% if request.path == register %}active{% endif %}">
        <a href="{% url 'register' %}" class="nav-link">
          <span class="fas fa-user-plus"></span>
          Registro
        </a>
      </li>
      <li class="navbar-item {% if request.path == login %}active{% endif %}">
        <a href="{% url 'login' %}" class="nav-link">
          <span class="fas fa-user"></span>
          Login
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>